### ISSUE TITLE
What is the argument called m in all methods

### ISSUE THREAD

**Issue by pedromaironi** [i32ropie/lol#6]
All methods have a parameter called m, What is that?
How can I get that m

**Comment by i32ropie** [comment]
It is the message :) you can see more info about that here https://github.com/eternnoir/pyTelegramBotAPI

**Comment by pedromaironi** [comment]
## New problem
- I'm new to python but I don't understand why if I want to write the data in the json it doesn't let me reply with reply_to () but if I start writing in the json before it does it but it doesn't respond

```
from config import *

@bot.message_handler(commands=['start'])
def commanStart(message):
    uname = message.from_user.first_name
    cid = message.chat.id
    uid = message.from_user.id
    date = message.date
    bot.reply_to(message, "Hola " + uname + "\n" + responses['start_2']['es'] + "\n" + "/register para registrarte en la tienda para tu compra", reply_markup=markup)
    data = {"id:": m.from_user.id,"name":m.from_user.first_name,"lastname":m.from_user.last_name,"username":m.from_user.username,"language_code":m.from_user.language_code}
    with open('extra_data/user.json', 'w') as f:
        json.dump(data, f)
```

**Comment by i32ropie** [comment]
Hi :) You can contact me directly through Telegram at [@edurolp](https://telegram.me/edurolp) and I can help you there more easily.

**Comment by pedromaironi** [comment]
Thank u, close this issue
